pip install -U adodbapi        
pip install -U bson            
pip install -U certifi         
pip install -U cffi            
pip install -U chardet         
pip install -U cryptography    
pip install -U cssselect       
pip install -U docxtpl         
pip install -U enum            
pip install -U enum34          
pip install -U http            
pip install -U idna            
pip install -U ipaddress       
pip install -U Jinja2          
pip install -U lxml            
pip install -U MarkupSafe        
pip install -U ndg-httpsclient 
pip install -U olefile         
pip install -U phantomjs       
pip install -U PIL             
pip install -U Pillow                    
pip install -U progressbar     
pip install -U py2exe          
pip install -U pyasn1          
pip install -U pycparser       
pip install -U pymongo         
pip install -U pyOpenSSL       
pip install -U pypiwin32       
pip install -U pyreadline      
pip install -U pytesseract     
pip install -U python-dateutil 
pip install -U python-docx     
pip install -U pytz            
pip install -U pywin32         
pip install -U requests        
pip install -U selenium        
pip install -U setuptools      
pip install -U six             
pip install -U tesseract       
pip install -U urllib3         
pip install -U win10toast      
pip install -U wincertstore